apiVersion: apps/v1
kind: Deployment
metadata:
  name: examplerepo
  labels:
    app: examplerepo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: examplerepo
  template:
    metadata:
      labels:
        app: examplerepo
    spec:
      containers:
        - name: examplerepo
          image: terrenceskill/examplerepo:0892017eff8762b86b53394d1fec42e7063e1d25
          ports:
            - containerPort: 3000