apiVersion: apps/v1
kind: Deployment
metadata:
  name: examplerepo
  labels:
    app: examplerepo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: examplerepo
  template:
    metadata:
      labels:
        app: examplerepo
    spec:
      containers:
        - name: examplerepo
          image: terrenceskill/examplerepo:8fbebb14343dadf71862d939e406a9399a1d1a8e
          ports:
            - containerPort: 3000